version: '3.9'

services:
  postgres:
    ports:
      - "5433:5432"

  minio:
    ports:
      - "9003:9000"
      - "9004:9001"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./backend:/app
    ports:
      - "4000:3000"
      - "4001:3001"

  frontend-pwa:
    image: nginx:alpine
    ports:
      - "8083:80"
    volumes:
      - ./frontend-pwa:/usr/share/nginx/html

  frontend-metaverse:
    image: nginx:alpine
    ports:
      - "8084:80"
    volumes:
      - ./frontend-metaverse:/usr/share/nginx/html

  nginx:
    ports:
      - "80:80"
